### ISSUE TITLE
Site not working on IE

### ISSUE THREAD

**Issue by kevinfalting** [22arw/airshow#18]
When viewing the site on any mil computer, the site looks broken or does not load at all

**Comment by Dynathy** [comment]
Fixed by modifing pollyfil.ts, 
The compatibility it is intially disabled through the use of comment sections. 

Removing the comment sections as described will allow angular to work as advertised.

**Comment by kevinfalting** [comment]
What exactly did you uncomment? Copy and paste that here.

**Comment by kevinfalting** [comment]
When I pulled it down to my macbook and compiled it, it gave me the following error:
```
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'classlist.js' in '/Users/kevinfalting/Development/airshow/src'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'web-animations-js' in '/Users/kevinfalting/Development/airshow/src'
```
I then ran `npm install` which fixed it.
